In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
arquivo = "../data/raw/Municipio_Mensal_1T_2026.xlsx"

In [3]:
excel = pd.ExcelFile(arquivo)

In [4]:
excel.sheet_names

['Número de UC', 'Consumo MWh']

In [5]:
df = pd.read_excel(arquivo, sheet_name="Consumo MWh")

In [6]:
df.head()

,tipo,cod_muni,agência,núcleo,unidade,município,cod_classe,classe,1994-01-01 00:00:00,1994-02-01 00:00:00,...,2025-06-01 00:00:00,2025-07-01 00:00:00,2025-08-01 00:00:00,2025-09-01 00:00:00,2025-10-01 00:00:00,2025-11-01 00:00:00,2025-12-01 00:00:00,2026-01-01 00:00:00,2026-02-01 00:00:00,2026-03-01 00:00:00
0,Cativo,1101,ARFLO,Núcleo Grande Capital,Florianópolis (sede),Florianópolis,1,Residencial,21357.147,20782.785,...,52878.556648,60441.735810,54284.838228,58371.440918,53787.994558,53800.328053,56821.529842,87456.494352,86524.998202,83895.217345
1,Cativo,1101,ARFLO,Núcleo Grande Capital,Florianópolis (sede),Florianópolis,2,Industrial,1698.383,1641.103,...,2558.042630,2877.644839,2557.793542,2761.337071,2972.536314,2669.177959,2677.598859,3332.905398,3222.091413,3746.075399
2,Cativo,1101,ARFLO,Núcleo Grande Capital,Florianópolis (sede),Florianópolis,3,Comercial,14766.175,13420.879,...,24422.064633,22060.793725,23029.908608,23087.512572,22567.306346,22916.987372,24222.198117,30172.991984,32276.237126,35388.860964
3,Cativo,1101,ARFLO,Núcleo Grande Capital,Florianópolis (sede),Florianópolis,4,Rural,25.908,23.863,...,37.052000,43.193000,29.520000,37.073000,37.665,38.949800,43.244000,50.350000,33.971450,42.984200
4,Cativo,1101,ARFLO,Núcleo Grande Capital,Florianópolis (sede),Florianópolis,5,Poder Público,6393.112,4903.650,...,6667.282925,7209.118309,6673.288946,6409.265993,6528.080709,7015.699795,6543.715033,7558.026813,8207.902689,8857.708610

In [7]:
df.shape

(7716, 395)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7716 entries, 0 to 7715
Columns: 395 entries, tipo to 2026-03-01 00:00:00
dtypes: float64(386), int64(2), object(1), str(6)
memory usage: 23.3+ MB

In [9]:
df.tail(5)

,tipo,cod_muni,agência,núcleo,unidade,município,cod_classe,classe,1994-01-01 00:00:00,1994-02-01 00:00:00,...,2025-06-01 00:00:00,2025-07-01 00:00:00,2025-08-01 00:00:00,2025-09-01 00:00:00,2025-10-01 00:00:00,2025-11-01 00:00:00,2025-12-01 00:00:00,2026-01-01 00:00:00,2026-02-01 00:00:00,2026-03-01 00:00:00
7711,Livre,17109,ARITA,Núcleo Leste,Itajaí (sede),Piçarras,2,Industrial,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.876050
7712,Livre,3101,ARJOI,Núcleo Norte,Joinville (sede),Joinville,2,Industrial,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.477670
7713,Livre,17108,ARITA,Núcleo Leste,Itajaí (sede),Barra Velha,2,Industrial,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.091900
7714,Livre,17110,ARITA,Núcleo Leste,Itajaí (sede),Penha,2,Industrial,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.759996
7715,Livre,7101,ARJSL,Núcleo Norte,Jaraguá do Sul (unidade),Jaraguá do Sul,2,Industrial,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.607623

In [10]:
df.columns

Index([             'tipo',          'cod_muni',           'agência',
                  'núcleo',           'unidade',         'município',
              'cod_classe',            'classe', 1994-01-01 00:00:00,
       1994-02-01 00:00:00,
       ...
       2025-06-01 00:00:00, 2025-07-01 00:00:00, 2025-08-01 00:00:00,
       2025-09-01 00:00:00, 2025-10-01 00:00:00, 2025-11-01 00:00:00,
       2025-12-01 00:00:00, 2026-01-01 00:00:00, 2026-02-01 00:00:00,
       2026-03-01 00:00:00],
      dtype='object', length=395)

In [11]:
df["município"].nunique()

290

In [12]:
df["município"].unique()

<StringArray>
[            'Florianópolis',                  'São José',
                   'Palhoça', 'Santo Amaro da Imperatriz',
              'Águas Mornas',                   'Biguaçu',
            'Antônio Carlos',    'Governador Celso Ramos',
                   'Tijucas',                 'Canelinha',
 ...
                'Sul Brasil',            'Lageado Grande',
              'Jardinópolis',                     'Irati',
                    'Ipuaçu',               'Águas Frias',
           'Santiago do Sul',                     'Jupiá',
                 'Bom Jesus',        'Bom Jesus do Oeste']
Length: 290, dtype: str

In [13]:
df["classe"].value_counts()

classe
Industrial            2696
Comercial             2591
Revenda                477
Serviço Público        455
Rural                  326
Poder Público          301
Residencial            290
Iluminação Pública     290
Próprio                290
Name: count, dtype: int64

In [14]:
df["tipo"].value_counts()

tipo
Livre     5106
Cativo    2610
Name: count, dtype: int64

In [15]:
df["agência"].value_counts()

agência
ARBLU    984
ARFLO    952
ARITA    686
ARJOI    678
ARCHA    612
ARCRI    554
ARRSL    475
ARSMO    451
ARLAG    426
ARTUB    399
ARJOA    292
ARVID    288
ARJSL    266
ARCON    259
ARMAF    245
ARSBS    149
Name: count, dtype: int64

In [16]:
df.groupby("município").size().sort_values(ascending=False)

município
Joinville                 486
Florianópolis             335
Blumenau                  274
Itajaí                    215
Brusque                   175
                         ...
Belmonte                    9
Tigrinhos                   9
São Pedro de Alcântara      9
Tunápolis                   9
Treze de Maio               9
Length: 290, dtype: int64

In [17]:
df[df["município"] == "Joinville"][["município", "classe", "tipo"]]

      município         classe    tipo
297   Joinville    Residencial  Cativo
298   Joinville     Industrial  Cativo
299   Joinville      Comercial  Cativo
300   Joinville          Rural  Cativo
301   Joinville  Poder Público  Cativo
...         ...            ...     ...
7688  Joinville      Comercial   Livre
7695  Joinville      Comercial   Livre
7708  Joinville      Comercial   Livre
7709  Joinville      Comercial   Livre
7712  Joinville     Industrial   Livre

[486 rows x 3 columns]

In [18]:
df[df["município"] == "Belmonte"][["município", "classe", "tipo"]]

     município              classe    tipo
1458  Belmonte         Residencial  Cativo
1459  Belmonte          Industrial  Cativo
1460  Belmonte           Comercial  Cativo
1461  Belmonte               Rural  Cativo
1462  Belmonte       Poder Público  Cativo
1463  Belmonte  Iluminação Pública  Cativo
1464  Belmonte     Serviço Público  Cativo
1465  Belmonte             Próprio  Cativo
1466  Belmonte             Revenda  Cativo

In [19]:
df[df["município"] == "Joinville"][["classe", "tipo"]].drop_duplicates()

                  classe    tipo
297          Residencial  Cativo
298           Industrial  Cativo
299            Comercial  Cativo
300                Rural  Cativo
301        Poder Público  Cativo
302   Iluminação Pública  Cativo
303      Serviço Público  Cativo
304              Próprio  Cativo
305              Revenda  Cativo
2612          Industrial   Livre
2695           Comercial   Livre
4189     Serviço Público   Livre
7533       Poder Público   Livre

In [20]:
df[df["município"] == "Belmonte"][["classe", "tipo"]].drop_duplicates()

                  classe    tipo
1458         Residencial  Cativo
1459          Industrial  Cativo
1460           Comercial  Cativo
1461               Rural  Cativo
1462       Poder Público  Cativo
1463  Iluminação Pública  Cativo
1464     Serviço Público  Cativo
1465             Próprio  Cativo
1466             Revenda  Cativo

In [21]:
df[df["município"] == "Joinville"]["unidade"].value_counts()

unidade
Joinville (sede)    486
Name: count, dtype: int64

In [22]:
df[df["município"] == "Joinville"]["núcleo"].value_counts()

núcleo
Núcleo Norte    486
Name: count, dtype: int64

In [23]:
df.columns.tolist()

['tipo',
 'cod_muni',
 'agência',
 'núcleo',
 'unidade',
 'município',
 'cod_classe',
 'classe',
 datetime.datetime(1994, 1, 1, 0, 0),
 datetime.datetime(1994, 2, 1, 0, 0),
 datetime.datetime(1994, 3, 1, 0, 0),
 datetime.datetime(1994, 4, 1, 0, 0),
 datetime.datetime(1994, 5, 1, 0, 0),
 datetime.datetime(1994, 6, 1, 0, 0),
 datetime.datetime(1994, 7, 1, 0, 0),
 datetime.datetime(1994, 8, 1, 0, 0),
 datetime.datetime(1994, 9, 1, 0, 0),
 datetime.datetime(1994, 10, 1, 0, 0),
 datetime.datetime(1994, 11, 1, 0, 0),
 datetime.datetime(1994, 12, 1, 0, 0),
 datetime.datetime(1995, 1, 1, 0, 0),
 datetime.datetime(1995, 2, 1, 0, 0),
 datetime.datetime(1995, 3, 1, 0, 0),
 datetime.datetime(1995, 4, 1, 0, 0),
 datetime.datetime(1995, 5, 1, 0, 0),
 datetime.datetime(1995, 6, 1, 0, 0),
 datetime.datetime(1995, 7, 1, 0, 0),
 datetime.datetime(1995, 8, 1, 0, 0),
 datetime.datetime(1995, 9, 1, 0, 0),
 datetime.datetime(1995, 10, 1, 0, 0),
 datetime.datetime(1995, 11, 1, 0, 0),
 datetime.datetime(1995, 12, 1, 0, 0),
 datetime.datetime(1996, 1, 1, 0, 0),
 datetime.datetime(1996, 2, 1, 0, 0),
 datetime.datetime(1996, 3, 1, 0, 0),
 datetime.datetime(1996, 4, 1, 0, 0),
 datetime.datetime(1996, 5, 1, 0, 0),
 datetime.datetime(1996, 6, 1, 0, 0),
 datetime.datetime(1996, 7, 1, 0, 0),
 datetime.datetime(1996, 8, 1, 0, 0),
 datetime.datetime(1996, 9, 1, 0, 0),
 datetime.datetime(1996, 10, 1, 0, 0),
 datetime.datetime(1996, 11, 1, 0, 0),
 datetime.datetime(1996, 12, 1, 0, 0),
 datetime.datetime(1997, 1, 1, 0, 0),
 datetime.datetime(1997, 2, 1, 0, 0),
 datetime.datetime(1997, 3, 1, 0, 0),
 datetime.datetime(1997, 4, 1, 0, 0),
 datetime.datetime(1997, 5, 1, 0, 0),
 datetime.datetime(1997, 6, 1, 0, 0),
 datetime.datetime(1997, 7, 1, 0, 0),
 datetime.datetime(1997, 8, 1, 0, 0),
 datetime.datetime(1997, 9, 1, 0, 0),
 datetime.datetime(1997, 10, 1, 0, 0),
 datetime.datetime(1997, 11, 1, 0, 0),
 datetime.datetime(1997, 12, 1, 0, 0),
 datetime.datetime(1998, 1, 1, 0, 0),
 datetime.datetime(1998, 2, 1, 0, 0),
 datetime.datetime(1998, 3, 1, 0, 0),
 datetime.datetime(1998, 4, 1, 0, 0),
 datetime.datetime(1998, 5, 1, 0, 0),
 datetime.datetime(1998, 6, 1, 0, 0),
 datetime.datetime(1998, 7, 1, 0, 0),
 datetime.datetime(1998, 8, 1, 0, 0),
 datetime.datetime(1998, 9, 1, 0, 0),
 datetime.datetime(1998, 10, 1, 0, 0),
 datetime.datetime(1998, 11, 1, 0, 0),
 datetime.datetime(1998, 12, 1, 0, 0),
 datetime.datetime(1999, 1, 1, 0, 0),
 datetime.datetime(1999, 2, 1, 0, 0),
 datetime.datetime(1999, 3, 1, 0, 0),
 datetime.datetime(1999, 4, 1, 0, 0),
 datetime.datetime(1999, 5, 1, 0, 0),
 datetime.datetime(1999, 6, 1, 0, 0),
 datetime.datetime(1999, 7, 1, 0, 0),
 datetime.datetime(1999, 8, 1, 0, 0),
 datetime.datetime(1999, 9, 1, 0, 0),
 datetime.datetime(1999, 10, 1, 0, 0),
 datetime.datetime(1999, 11, 1, 0, 0),
 datetime.datetime(1999, 12, 1, 0, 0),
 datetime.datetime(2000, 1, 1, 0, 0),
 datetime.datetime(2000, 2, 1, 0, 0),
 datetime.datetime(2000, 3, 1, 0, 0),
 datetime.datetime(2000, 4, 1, 0, 0),
 datetime.datetime(2000, 5, 1, 0, 0),
 datetime.datetime(2000, 6, 1, 0, 0),
 datetime.datetime(2000, 7, 1, 0, 0),
 datetime.datetime(2000, 8, 1, 0, 0),
 datetime.datetime(2000, 9, 1, 0, 0),
 datetime.datetime(2000, 10, 1, 0, 0),
 datetime.datetime(2000, 11, 1, 0, 0),
 datetime.datetime(2000, 12, 1, 0, 0),
 datetime.datetime(2001, 1, 1, 0, 0),
 datetime.datetime(2001, 2, 1, 0, 0),
 datetime.datetime(2001, 3, 1, 0, 0),
 datetime.datetime(2001, 4, 1, 0, 0),
 datetime.datetime(2001, 5, 1, 0, 0),
 datetime.datetime(2001, 6, 1, 0, 0),
 datetime.datetime(2001, 7, 1, 0, 0),
 datetime.datetime(2001, 8, 1, 0, 0),
 datetime.datetime(2001, 9, 1, 0, 0),
 datetime.datetime(2001, 10, 1, 0, 0),
 datetime.datetime(2001, 11, 1, 0, 0),
 datetime.datetime(2001, 12, 1, 0, 0),
 datetime.datetime(2002, 1, 1, 0, 0),
 datetime.datetime(2002, 2, 1, 0, 0),
 datetime.datetime(2002, 3, 1, 0, 0),
 datetime.datetime(2002, 4, 1, 0, 0),
 datetime.datetime(2002, 5, 1, 0, 0),
 datetime.datetime(2002, 6, 1, 0, 0),
 datetime.datetime(2002, 7, 1, 0, 0),
 datetime.datetime(2002, 8, 1, 0, 0),
 datetime.datetime(2002, 9, 1, 0, 0),
 datetime.datetime(2002, 10, 1, 0, 0),
 datetime.datetime(2002, 11, 1, 0, 0),
 datetime.datetime(2002, 12, 1, 0, 0),
 datetime.datetime(2003, 1, 1, 0, 0),
 datetime.datetime(2003, 2, 1, 0, 0),
 datetime.datetime(2003, 3, 1, 0, 0),
 datetime.datetime(2003, 4, 1, 0, 0),
 datetime.datetime(2003, 5, 1, 0, 0),
 datetime.datetime(2003, 6, 1, 0, 0),
 datetime.datetime(2003, 7, 1, 0, 0),
 datetime.datetime(2003, 8, 1, 0, 0),
 datetime.datetime(2003, 9, 1, 0, 0),
 datetime.datetime(2003, 10, 1, 0, 0),
 datetime.datetime(2003, 11, 1, 0, 0),
 datetime.datetime(2003, 12, 1, 0, 0),
 datetime.datetime(2004, 1, 1, 0, 0),
 datetime.datetime(2004, 2, 1, 0, 0),
 datetime.datetime(2004, 3, 1, 0, 0),
 datetime.datetime(2004, 4, 1, 0, 0),
 datetime.datetime(2004, 5, 1, 0, 0),
 datetime.datetime(2004, 6, 1, 0, 0),
 datetime.datetime(2004, 7, 1, 0, 0),
 datetime.datetime(2004, 8, 1, 0, 0),
 datetime.datetime(2004, 9, 1, 0, 0),
 datetime.datetime(2004, 10, 1, 0, 0),
 datetime.datetime(2004, 11, 1, 0, 0),
 datetime.datetime(2004, 12, 1, 0, 0),
 datetime.datetime(2005, 1, 1, 0, 0),
 datetime.datetime(2005, 2, 1, 0, 0),
 datetime.datetime(2005, 3, 1, 0, 0),
 datetime.datetime(2005, 4, 1, 0, 0),
 datetime.datetime(2005, 5, 1, 0, 0),
 datetime.datetime(2005, 6, 1, 0, 0),
 datetime.datetime(2005, 7, 1, 0, 0),
 datetime.datetime(2005, 8, 1, 0, 0),
 datetime.datetime(2005, 9, 1, 0, 0),
 datetime.datetime(2005, 10, 1, 0, 0),
 datetime.datetime(2005, 11, 1, 0, 0),
 datetime.datetime(2005, 12, 1, 0, 0),
 datetime.datetime(2006, 1, 1, 0, 0),
 datetime.datetime(2006, 2, 1, 0, 0),
 datetime.datetime(2006, 3, 1, 0, 0),
 datetime.datetime(2006, 4, 1, 0, 0),
 datetime.datetime(2006, 5, 1, 0, 0),
 datetime.datetime(2006, 6, 1, 0, 0),
 datetime.datetime(2006, 7, 1, 0, 0),
 datetime.datetime(2006, 8, 1, 0, 0),
 datetime.datetime(2006, 9, 1, 0, 0),
 datetime.datetime(2006, 10, 1, 0, 0),
 datetime.datetime(2006, 11, 1, 0, 0),
 datetime.datetime(2006, 12, 1, 0, 0),
 datetime.datetime(2007, 1, 1, 0, 0),
 datetime.datetime(2007, 2, 1, 0, 0),
 datetime.datetime(2007, 3, 1, 0, 0),
 datetime.datetime(2007, 4, 1, 0, 0),
 datetime.datetime(2007, 5, 1, 0, 0),
 datetime.datetime(2007, 6, 1, 0, 0),
 datetime.datetime(2007, 7, 1, 0, 0),
 datetime.datetime(2007, 8, 1, 0, 0),
 datetime.datetime(2007, 9, 1, 0, 0),
 datetime.datetime(2007, 10, 1, 0, 0),
 datetime.datetime(2007, 11, 1, 0, 0),
 datetime.datetime(2007, 12, 1, 0, 0),
 datetime.datetime(2008, 1, 1, 0, 0),
 datetime.datetime(2008, 2, 1, 0, 0),
 datetime.datetime(2008, 3, 1, 0, 0),
 datetime.datetime(2008, 4, 1, 0, 0),
 datetime.datetime(2008, 5, 1, 0, 0),
 datetime.datetime(2008, 6, 1, 0, 0),
 datetime.datetime(2008, 7, 1, 0, 0),
 datetime.datetime(2008, 8, 1, 0, 0),
 datetime.datetime(2008, 9, 1, 0, 0),
 datetime.datetime(2008, 10, 1, 0, 0),
 datetime.datetime(2008, 11, 1, 0, 0),
 datetime.datetime(2008, 12, 1, 0, 0),
 datetime.datetime(2009, 1, 1, 0, 0),
 datetime.datetime(2009, 2, 1, 0, 0),
 datetime.datetime(2009, 3, 1, 0, 0),
 datetime.datetime(2009, 4, 1, 0, 0),
 datetime.datetime(2009, 5, 1, 0, 0),
 datetime.datetime(2009, 6, 1, 0, 0),
 datetime.datetime(2009, 7, 1, 0, 0),
 datetime.datetime(2009, 8, 1, 0, 0),
 datetime.datetime(2009, 9, 1, 0, 0),
 datetime.datetime(2009, 10, 1, 0, 0),
 datetime.datetime(2009, 11, 1, 0, 0),
 datetime.datetime(2009, 12, 1, 0, 0),
 datetime.datetime(2010, 1, 1, 0, 0),
 datetime.datetime(2010, 2, 1, 0, 0),
 datetime.datetime(2010, 3, 1, 0, 0),
 datetime.datetime(2010, 4, 1, 0, 0),
 datetime.datetime(2010, 5, 1, 0, 0),
 datetime.datetime(2010, 6, 1, 0, 0),
 datetime.datetime(2010, 7, 1, 0, 0),
 datetime.datetime(2010, 8, 1, 0, 0),
 datetime.datetime(2010, 9, 1, 0, 0),
 datetime.datetime(2010, 10, 1, 0, 0),
 datetime.datetime(2010, 11, 1, 0, 0),
 datetime.datetime(2010, 12, 1, 0, 0),
 datetime.datetime(2011, 1, 1, 0, 0),
 datetime.datetime(2011, 2, 1, 0, 0),
 datetime.datetime(2011, 3, 1, 0, 0),
 datetime.datetime(2011, 4, 1, 0, 0),
 datetime.datetime(2011, 5, 1, 0, 0),
 datetime.datetime(2011, 6, 1, 0, 0),
 datetime.datetime(2011, 7, 1, 0, 0),
 datetime.datetime(2011, 8, 1, 0, 0),
 datetime.datetime(2011, 9, 1, 0, 0),
 datetime.datetime(2011, 10, 1, 0, 0),
 datetime.datetime(2011, 11, 1, 0, 0),
 datetime.datetime(2011, 12, 1, 0, 0),
 datetime.datetime(2012, 1, 1, 0, 0),
 datetime.datetime(2012, 2, 1, 0, 0),
 datetime.datetime(2012, 3, 1, 0, 0),
 datetime.datetime(2012, 4, 1, 0, 0),
 datetime.datetime(2012, 5, 1, 0, 0),
 datetime.datetime(2012, 6, 1, 0, 0),
 datetime.datetime(2012, 7, 1, 0, 0),
 datetime.datetime(2012, 8, 1, 0, 0),
 datetime.datetime(2012, 9, 1, 0, 0),
 datetime.datetime(2012, 10, 1, 0, 0),
 datetime.datetime(2012, 11, 1, 0, 0),
 datetime.datetime(2012, 12, 1, 0, 0),
 datetime.datetime(2013, 1, 1, 0, 0),
 datetime.datetime(2013, 2, 1, 0, 0),
 datetime.datetime(2013, 3, 1, 0, 0),
 datetime.datetime(2013, 4, 1, 0, 0),
 datetime.datetime(2013, 5, 1, 0, 0),
 datetime.datetime(2013, 6, 1, 0, 0),
 datetime.datetime(2013, 7, 1, 0, 0),
 datetime.datetime(2013, 8, 1, 0, 0),
 datetime.datetime(2013, 9, 1, 0, 0),
 datetime.datetime(2013, 10, 1, 0, 0),
 datetime.datetime(2013, 11, 1, 0, 0),
 datetime.datetime(2013, 12, 1, 0, 0),
 datetime.datetime(2014, 1, 1, 0, 0),
 datetime.datetime(2014, 2, 1, 0, 0),
 datetime.datetime(2014, 3, 1, 0, 0),
 datetime.datetime(2014, 4, 1, 0, 0),
 datetime.datetime(2014, 5, 1, 0, 0),
 datetime.datetime(2014, 6, 1, 0, 0),
 datetime.datetime(2014, 7, 1, 0, 0),
 datetime.datetime(2014, 8, 1, 0, 0),
 datetime.datetime(2014, 9, 1, 0, 0),
 datetime.datetime(2014, 10, 1, 0, 0),
 datetime.datetime(2014, 11, 1, 0, 0),
 datetime.datetime(2014, 12, 1, 0, 0),
 datetime.datetime(2015, 1, 1, 0, 0),
 datetime.datetime(2015, 2, 1, 0, 0),
 datetime.datetime(2015, 3, 1, 0, 0),
 datetime.datetime(2015, 4, 1, 0, 0),
 datetime.datetime(2015, 5, 1, 0, 0),
 datetime.datetime(2015, 6, 1, 0, 0),
 datetime.datetime(2015, 7, 1, 0, 0),
 datetime.datetime(2015, 8, 1, 0, 0),
 datetime.datetime(2015, 9, 1, 0, 0),
 datetime.datetime(2015, 10, 1, 0, 0),
 datetime.datetime(2015, 11, 1, 0, 0),
 datetime.datetime(2015, 12, 1, 0, 0),
 datetime.datetime(2016, 1, 1, 0, 0),
 datetime.datetime(2016, 2, 1, 0, 0),
 datetime.datetime(2016, 3, 1, 0, 0),
 datetime.datetime(2016, 4, 1, 0, 0),
 datetime.datetime(2016, 5, 1, 0, 0),
 datetime.datetime(2016, 6, 1, 0, 0),
 datetime.datetime(2016, 7, 1, 0, 0),
 datetime.datetime(2016, 8, 1, 0, 0),
 datetime.datetime(2016, 9, 1, 0, 0),
 datetime.datetime(2016, 10, 1, 0, 0),
 datetime.datetime(2016, 11, 1, 0, 0),
 datetime.datetime(2016, 12, 1, 0, 0),
 datetime.datetime(2017, 1, 1, 0, 0),
 datetime.datetime(2017, 2, 1, 0, 0),
 datetime.datetime(2017, 3, 1, 0, 0),
 datetime.datetime(2017, 4, 1, 0, 0),
 datetime.datetime(2017, 5, 1, 0, 0),
 datetime.datetime(2017, 6, 1, 0, 0),
 datetime.datetime(2017, 7, 1, 0, 0),
 datetime.datetime(2017, 8, 1, 0, 0),
 datetime.datetime(2017, 9, 1, 0, 0),
 datetime.datetime(2017, 10, 1, 0, 0),
 datetime.datetime(2017, 11, 1, 0, 0),
 datetime.datetime(2017, 12, 1, 0, 0),
 datetime.datetime(2018, 1, 1, 0, 0),
 datetime.datetime(2018, 2, 1, 0, 0),
 datetime.datetime(2018, 3, 1, 0, 0),
 datetime.datetime(2018, 4, 1, 0, 0),
 datetime.datetime(2018, 5, 1, 0, 0),
 datetime.datetime(2018, 6, 1, 0, 0),
 datetime.datetime(2018, 7, 1, 0, 0),
 datetime.datetime(2018, 8, 1, 0, 0),
 datetime.datetime(2018, 9, 1, 0, 0),
 datetime.datetime(2018, 10, 1, 0, 0),
 datetime.datetime(2018, 11, 1, 0, 0),
 datetime.datetime(2018, 12, 1, 0, 0),
 datetime.datetime(2019, 1, 1, 0, 0),
 datetime.datetime(2019, 2, 1, 0, 0),
 datetime.datetime(2019, 3, 1, 0, 0),
 datetime.datetime(2019, 4, 1, 0, 0),
 datetime.datetime(2019, 5, 1, 0, 0),
 datetime.datetime(2019, 6, 1, 0, 0),
 datetime.datetime(2019, 7, 1, 0, 0),
 datetime.datetime(2019, 8, 1, 0, 0),
 datetime.datetime(2019, 9, 1, 0, 0),
 datetime.datetime(2019, 10, 1, 0, 0),
 datetime.datetime(2019, 11, 1, 0, 0),
 datetime.datetime(2019, 12, 1, 0, 0),
 datetime.datetime(2020, 1, 1, 0, 0),
 datetime.datetime(2020, 2, 1, 0, 0),
 datetime.datetime(2020, 3, 1, 0, 0),
 datetime.datetime(2020, 4, 1, 0, 0),
 datetime.datetime(2020, 5, 1, 0, 0),
 datetime.datetime(2020, 6, 1, 0, 0),
 datetime.datetime(2020, 7, 1, 0, 0),
 datetime.datetime(2020, 8, 1, 0, 0),
 datetime.datetime(2020, 9, 1, 0, 0),
 datetime.datetime(2020, 10, 1, 0, 0),
 datetime.datetime(2020, 11, 1, 0, 0),
 datetime.datetime(2020, 12, 1, 0, 0),
 datetime.datetime(2021, 1, 1, 0, 0),
 datetime.datetime(2021, 2, 1, 0, 0),
 datetime.datetime(2021, 3, 1, 0, 0),
 datetime.datetime(2021, 4, 1, 0, 0),
 datetime.datetime(2021, 5, 1, 0, 0),
 datetime.datetime(2021, 6, 1, 0, 0),
 datetime.datetime(2021, 7, 1, 0, 0),
 datetime.datetime(2021, 8, 1, 0, 0),
 datetime.datetime(2021, 9, 1, 0, 0),
 datetime.datetime(2021, 10, 1, 0, 0),
 datetime.datetime(2021, 11, 1, 0, 0),
 datetime.datetime(2021, 12, 1, 0, 0),
 datetime.datetime(2022, 1, 1, 0, 0),
 datetime.datetime(2022, 2, 1, 0, 0),
 datetime.datetime(2022, 3, 1, 0, 0),
 datetime.datetime(2022, 4, 1, 0, 0),
 datetime.datetime(2022, 5, 1, 0, 0),
 datetime.datetime(2022, 6, 1, 0, 0),
 datetime.datetime(2022, 7, 1, 0, 0),
 datetime.datetime(2022, 8, 1, 0, 0),
 datetime.datetime(2022, 9, 1, 0, 0),
 datetime.datetime(2022, 10, 1, 0, 0),
 datetime.datetime(2022, 11, 1, 0, 0),
 datetime.datetime(2022, 12, 1, 0, 0),
 datetime.datetime(2023, 1, 1, 0, 0),
 datetime.datetime(2023, 2, 1, 0, 0),
 datetime.datetime(2023, 3, 1, 0, 0),
 datetime.datetime(2023, 4, 1, 0, 0),
 datetime.datetime(2023, 5, 1, 0, 0),
 datetime.datetime(2023, 6, 1, 0, 0),
 datetime.datetime(2023, 7, 1, 0, 0),
 datetime.datetime(2023, 8, 1, 0, 0),
 datetime.datetime(2023, 9, 1, 0, 0),
 datetime.datetime(2023, 10, 1, 0, 0),
 datetime.datetime(2023, 11, 1, 0, 0),
 datetime.datetime(2023, 12, 1, 0, 0),
 datetime.datetime(2024, 1, 1, 0, 0),
 datetime.datetime(2024, 2, 1, 0, 0),
 datetime.datetime(2024, 3, 1, 0, 0),
 datetime.datetime(2024, 4, 1, 0, 0),
 datetime.datetime(2024, 5, 1, 0, 0),
 datetime.datetime(2024, 6, 1, 0, 0),
 datetime.datetime(2024, 7, 1, 0, 0),
 datetime.datetime(2024, 8, 1, 0, 0),
 datetime.datetime(2024, 9, 1, 0, 0),
 datetime.datetime(2024, 10, 1, 0, 0),
 datetime.datetime(2024, 11, 1, 0, 0),
 datetime.datetime(2024, 12, 1, 0, 0),
 datetime.datetime(2025, 1, 1, 0, 0),
 datetime.datetime(2025, 2, 1, 0, 0),
 datetime.datetime(2025, 3, 1, 0, 0),
 datetime.datetime(2025, 4, 1, 0, 0),
 datetime.datetime(2025, 5, 1, 0, 0),
 datetime.datetime(2025, 6, 1, 0, 0),
 datetime.datetime(2025, 7, 1, 0, 0),
 datetime.datetime(2025, 8, 1, 0, 0),
 datetime.datetime(2025, 9, 1, 0, 0),
 datetime.datetime(2025, 10, 1, 0, 0),
 datetime.datetime(2025, 11, 1, 0, 0),
 datetime.datetime(2025, 12, 1, 0, 0),
 datetime.datetime(2026, 1, 1, 0, 0),
 datetime.datetime(2026, 2, 1, 0, 0),
 datetime.datetime(2026, 3, 1, 0, 0)]

In [24]:
df[df["município"] == "Joinville"].nunique()

tipo                     2
cod_muni                 1
agência                  1
núcleo                   1
unidade                  1
                      ...
2025-11-01 00:00:00    435
2025-12-01 00:00:00    439
2026-01-01 00:00:00    449
2026-02-01 00:00:00    455
2026-03-01 00:00:00    467
Length: 395, dtype: int64

In [25]:
df[["tipo", "município", "classe"]].drop_duplicates()

        tipo      município           classe
0     Cativo  Florianópolis      Residencial
1     Cativo  Florianópolis       Industrial
2     Cativo  Florianópolis        Comercial
3     Cativo  Florianópolis            Rural
4     Cativo  Florianópolis    Poder Público
...      ...            ...              ...
7533   Livre      Joinville    Poder Público
7544   Livre    Celso Ramos       Industrial
7569   Livre  Correia Pinto  Serviço Público
7644   Livre       Piratuba  Serviço Público
7684   Livre         Imaruí       Industrial

[3086 rows x 3 columns]

In [26]:
df[["tipo", "município", "classe", "agência"]].drop_duplicates()

        tipo      município           classe agência
0     Cativo  Florianópolis      Residencial   ARFLO
1     Cativo  Florianópolis       Industrial   ARFLO
2     Cativo  Florianópolis        Comercial   ARFLO
3     Cativo  Florianópolis            Rural   ARFLO
4     Cativo  Florianópolis    Poder Público   ARFLO
...      ...            ...              ...     ...
7533   Livre      Joinville    Poder Público   ARJOI
7544   Livre    Celso Ramos       Industrial   ARLAG
7569   Livre  Correia Pinto  Serviço Público   ARLAG
7644   Livre       Piratuba  Serviço Público   ARJOA
7684   Livre         Imaruí       Industrial   ARTUB

[3086 rows x 4 columns]

In [27]:
df[["tipo", "município", "classe", "agência", "núcleo"]].drop_duplicates()

        tipo      município           classe agência                 núcleo
0     Cativo  Florianópolis      Residencial   ARFLO  Núcleo Grande Capital
1     Cativo  Florianópolis       Industrial   ARFLO  Núcleo Grande Capital
2     Cativo  Florianópolis        Comercial   ARFLO  Núcleo Grande Capital
3     Cativo  Florianópolis            Rural   ARFLO  Núcleo Grande Capital
4     Cativo  Florianópolis    Poder Público   ARFLO  Núcleo Grande Capital
...      ...            ...              ...     ...                    ...
7533   Livre      Joinville    Poder Público   ARJOI           Núcleo Norte
7544   Livre    Celso Ramos       Industrial   ARLAG        Núcleo Planalto
7569   Livre  Correia Pinto  Serviço Público   ARLAG        Núcleo Planalto
7644   Livre       Piratuba  Serviço Público   ARJOA      Núcleo Meio Oeste
7684   Livre         Imaruí       Industrial   ARTUB             Núcleo Sul

[3086 rows x 5 columns]

In [28]:
df.groupby(["tipo", "município", "classe"]).size().sort_values(ascending=False)

tipo    município      classe
Livre   Florianópolis  Comercial             278
        Joinville      Industrial            230
                       Comercial             227
        Blumenau       Comercial             143
        São José       Comercial             136
                                            ...
Cativo  Agrolândia     Rural                   1
                       Serviço Público         1
        Agronômica     Comercial               1
                       Iluminação Pública      1
        Taió           Industrial              1
Length: 3086, dtype: int64

In [29]:
df[df["município"] == "Florianópolis"]["unidade"].unique()

<StringArray>
['Florianópolis (sede)']
Length: 1, dtype: str

In [30]:
df[df["município"] == "Florianópolis"]["unidade"].nunique()

1

In [31]:
df[df["município"] == "Florianópolis"]["agência"].unique()

<StringArray>
['ARFLO']
Length: 1, dtype: str

In [33]:
for coluna in df.columns:
    print(coluna)

tipo
cod_muni
agência
núcleo
unidade
município
cod_classe
classe
1994-01-01 00:00:00
1994-02-01 00:00:00
1994-03-01 00:00:00
1994-04-01 00:00:00
1994-05-01 00:00:00
1994-06-01 00:00:00
1994-07-01 00:00:00
1994-08-01 00:00:00
1994-09-01 00:00:00
1994-10-01 00:00:00
1994-11-01 00:00:00
1994-12-01 00:00:00
1995-01-01 00:00:00
1995-02-01 00:00:00
1995-03-01 00:00:00
1995-04-01 00:00:00
1995-05-01 00:00:00
1995-06-01 00:00:00
1995-07-01 00:00:00
1995-08-01 00:00:00
1995-09-01 00:00:00
1995-10-01 00:00:00
1995-11-01 00:00:00
1995-12-01 00:00:00
1996-01-01 00:00:00
1996-02-01 00:00:00
1996-03-01 00:00:00
1996-04-01 00:00:00
1996-05-01 00:00:00
1996-06-01 00:00:00
1996-07-01 00:00:00
1996-08-01 00:00:00
1996-09-01 00:00:00
1996-10-01 00:00:00
1996-11-01 00:00:00
1996-12-01 00:00:00
1997-01-01 00:00:00
1997-02-01 00:00:00
1997-03-01 00:00:00
1997-04-01 00:00:00
1997-05-01 00:00:00
1997-06-01 00:00:00
1997-07-01 00:00:00
1997-08-01 00:00:00
1997-09-01 00:00:00
1997-10-01 00:00:00
1997-11-01 00:00:00
1997-12-01 00:00:00
1998-01-01 00:00:00
1998-02-01 00:00:00
1998-03-01 00:00:00
1998-04-01 00:00:00
1998-05-01 00:00:00
1998-06-01 00:00:00
1998-07-01 00:00:00
1998-08-01 00:00:00
1998-09-01 00:00:00
1998-10-01 00:00:00
1998-11-01 00:00:00
1998-12-01 00:00:00
1999-01-01 00:00:00
1999-02-01 00:00:00
1999-03-01 00:00:00
1999-04-01 00:00:00
1999-05-01 00:00:00
1999-06-01 00:00:00
1999-07-01 00:00:00
1999-08-01 00:00:00
1999-09-01 00:00:00
1999-10-01 00:00:00
1999-11-01 00:00:00
1999-12-01 00:00:00
2000-01-01 00:00:00
2000-02-01 00:00:00
2000-03-01 00:00:00
2000-04-01 00:00:00
2000-05-01 00:00:00
2000-06-01 00:00:00
2000-07-01 00:00:00
2000-08-01 00:00:00
2000-09-01 00:00:00
2000-10-01 00:00:00
2000-11-01 00:00:00
2000-12-01 00:00:00
2001-01-01 00:00:00
2001-02-01 00:00:00
2001-03-01 00:00:00
2001-04-01 00:00:00
2001-05-01 00:00:00
2001-06-01 00:00:00
2001-07-01 00:00:00
2001-08-01 00:00:00
2001-09-01 00:00:00
2001-10-01 00:00:00
2001-11-01 00:00:00
2001-12-01 00:00:00
2002-01-01 00:00:00
2002-02-01 00:00:00
2002-03-01 00:00:00
2002-04-01 00:00:00
2002-05-01 00:00:00
2002-06-01 00:00:00
2002-07-01 00:00:00
2002-08-01 00:00:00
2002-09-01 00:00:00
2002-10-01 00:00:00
2002-11-01 00:00:00
2002-12-01 00:00:00
2003-01-01 00:00:00
2003-02-01 00:00:00
2003-03-01 00:00:00
2003-04-01 00:00:00
2003-05-01 00:00:00
2003-06-01 00:00:00
2003-07-01 00:00:00
2003-08-01 00:00:00
2003-09-01 00:00:00
2003-10-01 00:00:00
2003-11-01 00:00:00
2003-12-01 00:00:00
2004-01-01 00:00:00
2004-02-01 00:00:00
2004-03-01 00:00:00
2004-04-01 00:00:00
2004-05-01 00:00:00
2004-06-01 00:00:00
2004-07-01 00:00:00
2004-08-01 00:00:00
2004-09-01 00:00:00
2004-10-01 00:00:00
2004-11-01 00:00:00
2004-12-01 00:00:00
2005-01-01 00:00:00
2005-02-01 00:00:00
2005-03-01 00:00:00
2005-04-01 00:00:00
2005-05-01 00:00:00
2005-06-01 00:00:00
2005-07-01 00:00:00
2005-08-01 00:00:00
2005-09-01 00:00:00
2005-10-01 00:00:00
2005-11-01 00:00:00
2005-12-01 00:00:00
2006-01-01 00:00:00
2006-02-01 00:00:00
2006-03-01 00:00:00
2006-04-01 00:00:00
2006-05-01 00:00:00
2006-06-01 00:00:00
2006-07-01 00:00:00
2006-08-01 00:00:00
2006-09-01 00:00:00
2006-10-01 00:00:00
2006-11-01 00:00:00
2006-12-01 00:00:00
2007-01-01 00:00:00
2007-02-01 00:00:00
2007-03-01 00:00:00
2007-04-01 00:00:00
2007-05-01 00:00:00
2007-06-01 00:00:00
2007-07-01 00:00:00
2007-08-01 00:00:00
2007-09-01 00:00:00
2007-10-01 00:00:00
2007-11-01 00:00:00
2007-12-01 00:00:00
2008-01-01 00:00:00
2008-02-01 00:00:00
2008-03-01 00:00:00
2008-04-01 00:00:00
2008-05-01 00:00:00
2008-06-01 00:00:00
2008-07-01 00:00:00
2008-08-01 00:00:00
2008-09-01 00:00:00
2008-10-01 00:00:00
2008-11-01 00:00:00
2008-12-01 00:00:00
2009-01-01 00:00:00
2009-02-01 00:00:00
2009-03-01 00:00:00
2009-04-01 00:00:00
2009-05-01 00:00:00
2009-06-01 00:00:00
2009-07-01 00:00:00
2009-08-01 00:00:00
2009-09-01 00:00:00
2009-10-01 00:00:00
2009-11-01 00:00:00
2009-12-01 00:00:00
2010-01-01 00:00:00
2010-02-01 00:00:00
2010-03-01 00:00:00
2010-04-01 00:00:00
2010-05-01 00:00:00
2010-06-01 00:00:00
2010-07-01 00:00:00
2010-08-01 00:00:00
2010-09-01 00:00:00
2010-10-01 00:00:00
2010-11-01 00:00:00
2010-12-01 00:00:00
2011-01-01 00:00:00
2011-02-01 00:00:00
2011-03-01 00:00:00
2011-04-01 00:00:00
2011-05-01 00:00:00
2011-06-01 00:00:00
2011-07-01 00:00:00
2011-08-01 00:00:00
2011-09-01 00:00:00
2011-10-01 00:00:00
2011-11-01 00:00:00
2011-12-01 00:00:00
2012-01-01 00:00:00
2012-02-01 00:00:00
2012-03-01 00:00:00
2012-04-01 00:00:00
2012-05-01 00:00:00
2012-06-01 00:00:00
2012-07-01 00:00:00
2012-08-01 00:00:00
2012-09-01 00:00:00
2012-10-01 00:00:00
2012-11-01 00:00:00
2012-12-01 00:00:00
2013-01-01 00:00:00
2013-02-01 00:00:00
2013-03-01 00:00:00
2013-04-01 00:00:00
2013-05-01 00:00:00
2013-06-01 00:00:00
2013-07-01 00:00:00
2013-08-01 00:00:00
2013-09-01 00:00:00
2013-10-01 00:00:00
2013-11-01 00:00:00
2013-12-01 00:00:00
2014-01-01 00:00:00
2014-02-01 00:00:00
2014-03-01 00:00:00
2014-04-01 00:00:00
2014-05-01 00:00:00
2014-06-01 00:00:00
2014-07-01 00:00:00
2014-08-01 00:00:00
2014-09-01 00:00:00
2014-10-01 00:00:00
2014-11-01 00:00:00
2014-12-01 00:00:00
2015-01-01 00:00:00
2015-02-01 00:00:00
2015-03-01 00:00:00
2015-04-01 00:00:00
2015-05-01 00:00:00
2015-06-01 00:00:00
2015-07-01 00:00:00
2015-08-01 00:00:00
2015-09-01 00:00:00
2015-10-01 00:00:00
2015-11-01 00:00:00
2015-12-01 00:00:00
2016-01-01 00:00:00
2016-02-01 00:00:00
2016-03-01 00:00:00
2016-04-01 00:00:00
2016-05-01 00:00:00
2016-06-01 00:00:00
2016-07-01 00:00:00
2016-08-01 00:00:00
2016-09-01 00:00:00
2016-10-01 00:00:00
2016-11-01 00:00:00
2016-12-01 00:00:00
2017-01-01 00:00:00
2017-02-01 00:00:00
2017-03-01 00:00:00
2017-04-01 00:00:00
2017-05-01 00:00:00
2017-06-01 00:00:00
2017-07-01 00:00:00
2017-08-01 00:00:00
2017-09-01 00:00:00
2017-10-01 00:00:00
2017-11-01 00:00:00
2017-12-01 00:00:00
2018-01-01 00:00:00
2018-02-01 00:00:00
2018-03-01 00:00:00
2018-04-01 00:00:00
2018-05-01 00:00:00
2018-06-01 00:00:00
2018-07-01 00:00:00
2018-08-01 00:00:00
2018-09-01 00:00:00
2018-10-01 00:00:00
2018-11-01 00:00:00
2018-12-01 00:00:00
2019-01-01 00:00:00
2019-02-01 00:00:00
2019-03-01 00:00:00
2019-04-01 00:00:00
2019-05-01 00:00:00
2019-06-01 00:00:00
2019-07-01 00:00:00
2019-08-01 00:00:00
2019-09-01 00:00:00
2019-10-01 00:00:00
2019-11-01 00:00:00
2019-12-01 00:00:00
2020-01-01 00:00:00
2020-02-01 00:00:00
2020-03-01 00:00:00
2020-04-01 00:00:00
2020-05-01 00:00:00
2020-06-01 00:00:00
2020-07-01 00:00:00
2020-08-01 00:00:00
2020-09-01 00:00:00
2020-10-01 00:00:00
2020-11-01 00:00:00
2020-12-01 00:00:00
2021-01-01 00:00:00
2021-02-01 00:00:00
2021-03-01 00:00:00
2021-04-01 00:00:00
2021-05-01 00:00:00
2021-06-01 00:00:00
2021-07-01 00:00:00
2021-08-01 00:00:00
2021-09-01 00:00:00
2021-10-01 00:00:00
2021-11-01 00:00:00
2021-12-01 00:00:00
2022-01-01 00:00:00
2022-02-01 00:00:00
2022-03-01 00:00:00
2022-04-01 00:00:00
2022-05-01 00:00:00
2022-06-01 00:00:00
2022-07-01 00:00:00
2022-08-01 00:00:00
2022-09-01 00:00:00
2022-10-01 00:00:00
2022-11-01 00:00:00
2022-12-01 00:00:00
2023-01-01 00:00:00
2023-02-01 00:00:00
2023-03-01 00:00:00
2023-04-01 00:00:00
2023-05-01 00:00:00
2023-06-01 00:00:00
2023-07-01 00:00:00
2023-08-01 00:00:00
2023-09-01 00:00:00
2023-10-01 00:00:00
2023-11-01 00:00:00
2023-12-01 00:00:00
2024-01-01 00:00:00
2024-02-01 00:00:00
2024-03-01 00:00:00
2024-04-01 00:00:00
2024-05-01 00:00:00
2024-06-01 00:00:00
2024-07-01 00:00:00
2024-08-01 00:00:00
2024-09-01 00:00:00
2024-10-01 00:00:00
2024-11-01 00:00:00
2024-12-01 00:00:00
2025-01-01 00:00:00
2025-02-01 00:00:00
2025-03-01 00:00:00
2025-04-01 00:00:00
2025-05-01 00:00:00
2025-06-01 00:00:00
2025-07-01 00:00:00
2025-08-01 00:00:00
2025-09-01 00:00:00
2025-10-01 00:00:00
2025-11-01 00:00:00
2025-12-01 00:00:00
2026-01-01 00:00:00
2026-02-01 00:00:00
2026-03-01 00:00:00

In [34]:
id_vars = [
    "tipo",
    "cod_muni",
    "agência",
    "núcleo",
    "unidade",
    "município",
    "cod_classe",
    "classe",
]

In [35]:
df_long = df.melt(id_vars=id_vars, var_name="data", value_name="consumo_mwh")

In [36]:
df_long.head()

,tipo,cod_muni,agência,núcleo,unidade,município,cod_classe,classe,data,consumo_mwh
0,Cativo,1101,ARFLO,Núcleo Grande Capital,Florianópolis (sede),Florianópolis,1,Residencial,1994-01-01 00:00:00,21357.147
1,Cativo,1101,ARFLO,Núcleo Grande Capital,Florianópolis (sede),Florianópolis,2,Industrial,1994-01-01 00:00:00,1698.383
2,Cativo,1101,ARFLO,Núcleo Grande Capital,Florianópolis (sede),Florianópolis,3,Comercial,1994-01-01 00:00:00,14766.175
3,Cativo,1101,ARFLO,Núcleo Grande Capital,Florianópolis (sede),Florianópolis,4,Rural,1994-01-01 00:00:00,25.908
4,Cativo,1101,ARFLO,Núcleo Grande Capital,Florianópolis (sede),Florianópolis,5,Poder Público,1994-01-01 00:00:00,6393.112