In [12]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
arquivo = "../data/raw/Municipio_Mensal_1T_2026.xlsx"

In [14]:
excel = pd.ExcelFile(arquivo)

In [15]:
excel.sheet_names

['Número de UC', 'Consumo MWh']

In [16]:
df = pd.read_excel(arquivo, sheet_name="Consumo MWh")

KeyboardInterrupt:

In [ ]:
df.head()

,tipo,cod_muni,agência,núcleo,unidade,município,cod_classe,classe,1994-01-01 00:00:00,1994-02-01 00:00:00,...,2025-06-01 00:00:00,2025-07-01 00:00:00,2025-08-01 00:00:00,2025-09-01 00:00:00,2025-10-01 00:00:00,2025-11-01 00:00:00,2025-12-01 00:00:00,2026-01-01 00:00:00,2026-02-01 00:00:00,2026-03-01 00:00:00
0,Cativo,1101,ARFLO,Núcleo Grande Capital,Florianópolis (sede),Florianópolis,1,Residencial,21357.147,20782.785,...,52878.556648,60441.735810,54284.838228,58371.440918,53787.994558,53800.328053,56821.529842,87456.494352,86524.998202,83895.217345
1,Cativo,1101,ARFLO,Núcleo Grande Capital,Florianópolis (sede),Florianópolis,2,Industrial,1698.383,1641.103,...,2558.042630,2877.644839,2557.793542,2761.337071,2972.536314,2669.177959,2677.598859,3332.905398,3222.091413,3746.075399
2,Cativo,1101,ARFLO,Núcleo Grande Capital,Florianópolis (sede),Florianópolis,3,Comercial,14766.175,13420.879,...,24422.064633,22060.793725,23029.908608,23087.512572,22567.306346,22916.987372,24222.198117,30172.991984,32276.237126,35388.860964
3,Cativo,1101,ARFLO,Núcleo Grande Capital,Florianópolis (sede),Florianópolis,4,Rural,25.908,23.863,...,37.052000,43.193000,29.520000,37.073000,37.665,38.949800,43.244000,50.350000,33.971450,42.984200
4,Cativo,1101,ARFLO,Núcleo Grande Capital,Florianópolis (sede),Florianópolis,5,Poder Público,6393.112,4903.650,...,6667.282925,7209.118309,6673.288946,6409.265993,6528.080709,7015.699795,6543.715033,7558.026813,8207.902689,8857.708610

In [ ]:
df.shape

(7716, 395)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7716 entries, 0 to 7715
Columns: 395 entries, tipo to 2026-03-01 00:00:00
dtypes: float64(386), int64(2), object(1), str(6)
memory usage: 23.3+ MB

In [18]:
df.tail(5)

,tipo,cod_muni,agência,núcleo,unidade,município,cod_classe,classe,1994-01-01 00:00:00,1994-02-01 00:00:00,...,2025-06-01 00:00:00,2025-07-01 00:00:00,2025-08-01 00:00:00,2025-09-01 00:00:00,2025-10-01 00:00:00,2025-11-01 00:00:00,2025-12-01 00:00:00,2026-01-01 00:00:00,2026-02-01 00:00:00,2026-03-01 00:00:00
7711,Livre,17109,ARITA,Núcleo Leste,Itajaí (sede),Piçarras,2,Industrial,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.876050
7712,Livre,3101,ARJOI,Núcleo Norte,Joinville (sede),Joinville,2,Industrial,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.477670
7713,Livre,17108,ARITA,Núcleo Leste,Itajaí (sede),Barra Velha,2,Industrial,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.091900
7714,Livre,17110,ARITA,Núcleo Leste,Itajaí (sede),Penha,2,Industrial,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.759996
7715,Livre,7101,ARJSL,Núcleo Norte,Jaraguá do Sul (unidade),Jaraguá do Sul,2,Industrial,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.607623

In [19]:
df.columns

Index([             'tipo',          'cod_muni',           'agência',
                  'núcleo',           'unidade',         'município',
              'cod_classe',            'classe', 1994-01-01 00:00:00,
       1994-02-01 00:00:00,
       ...
       2025-06-01 00:00:00, 2025-07-01 00:00:00, 2025-08-01 00:00:00,
       2025-09-01 00:00:00, 2025-10-01 00:00:00, 2025-11-01 00:00:00,
       2025-12-01 00:00:00, 2026-01-01 00:00:00, 2026-02-01 00:00:00,
       2026-03-01 00:00:00],
      dtype='object', length=395)

In [20]:
df["município"].nunique()

290

In [21]:
df["município"].unique()

<StringArray>
[            'Florianópolis',                  'São José',
                   'Palhoça', 'Santo Amaro da Imperatriz',
              'Águas Mornas',                   'Biguaçu',
            'Antônio Carlos',    'Governador Celso Ramos',
                   'Tijucas',                 'Canelinha',
 ...
                'Sul Brasil',            'Lageado Grande',
              'Jardinópolis',                     'Irati',
                    'Ipuaçu',               'Águas Frias',
           'Santiago do Sul',                     'Jupiá',
                 'Bom Jesus',        'Bom Jesus do Oeste']
Length: 290, dtype: str